general {
	output_format = "i3bar"
	colors = false
	markup = pango
	interval = 5
}

#order += "load"
#order += "cpu_temperature 0"
#order += "volume master"
order += "pomodoro_timer"
#order += "backlight"
order += "system_data"
#order += "ethernet _first_"
order += "volume_status"
order += "wireless _first_"
order += "battery_level"
order += "tztime local"

load {
	format = "<span foreground='#d8af60'>    </span><span foreground='#fdf6e3'>  %5min Load  </span>"
}

cpu_temperature 0 {
	format = "<span foreground='#e46c6d'>    </span><span foreground='#fdf6e3'>  %degrees °C  </span>"
	path = "/sys/class/thermal/thermal_zone1/temp"
}

wireless _first_ {
	format_up = "<span foreground='#68c7c1' rise='-1000' size='11000'>􀙇</span>" #<span foreground='#fdf6e3'>%essid</span>"
	format_down = "<span foreground='#68c7c1' size='11000'>􀙈</span>" #<span foreground='#fdf6e3'> Disconnected</span>"
}

volume_status {
    blocks = "􀊡􀊥􀊧􀊩"
	format = "<span foreground='#b899a8' rise='-500' size='11000'>{icon}</span>" # <span foreground='#fdf6e3'>{percentage}%</span>"
	format_muted = "<span foreground='#b899a8' rise='-1000' size='11000'>􀊣</span>" # <span foreground='#fdf6e3'>Silencio</span>"
    max_volume = 100
    cache_timeout = 3
}

battery 0 {
	last_full_capacity = true
	format = "<span foreground='#a3be8c' size='12000' rise='-1000'>  %status </span><span foreground='#fdf6e3' size='10000'>  %percentage  %remaining </span>"
#    <span foreground='#a3be8c'>  %status  </span><span foreground='#fdf6e3'>  %percentage  %remaining </span>"
	format_down = "Sen batería"
	status_chr = ""
	status_bat = ""
	status_unk = "Descoñecido"
	status_full = ""
	path = "/sys/class/power_supply/BAT%d/uevent"
	low_threshold = 10
	integer_battery_capacity = true
}

battery_level {
    # Refresh every second
    cache_timeout = 5
    threshold_full = 77
    threshold_degraded = 40
    blocks = "􀛪􀛩􀺶􀺸􀛨"
    #  blocks = "􀛪  􀛩  􀺶  􀺸  􀛨  "
    #  blocks = "          "
    charging_character = "􀢋"
    notify_low_level = true
    hide_when_full = true
    hide_seconds = true
    format = "<span foreground='#a3be8c' size='12000' rise='-1000'>{icon} </span><span foreground='#fdf6e3' size='10000'>{percent}%{time_remaining}</span>"
    color_charging = "#00FF00"
}

tztime local {
#
	format = "<span foreground='#f0c674' rise='-1000' size='12000'>􀧞 </span><span foreground='#fdf6e3'>%time </span>"
	format_time = " %a, %-d %b, %H:%M"
}

pomodoro_timer {
#􀎌
    format = "<span foreground='#a3be8c' rise='-1000' size='11000'> 􀠕</span><span foreground='#fdf6e3'>{mmss}</span>"
    format_active = "{format}"
    format_break = "{breakno} {format}"
    format_break_stopped = "{breakno} {format}"
    format_stopped = "<span foreground='#e46c6d' rise='-1000' size='11000'>􀠕</span><span foreground='#fdf6e3'></span>"
}

# Backlight: 􀡈  􀡏  􀡍  􀡎  􀡌
backlight {
        format = "<span foreground='#81a1c1' rise='-1000' size='11000'>􀆮 </span><span foreground='#fdf6e3'>{level}%</span>"
        cache_timeout = 3
}

system_data {
    cache_timeout = 5
    mem_threshold = 50
    cpu_threshold = 60

    cpu_format = "<span foreground='#81a1c1' rise='-1000'></span> <span foreground='#fdf6e3'>{cpu_used_percent:.2f}%</span>  "
    mem_format = "<span foreground='#81a1c1' rise='-1000'></span> <span foreground='#fdf6e3'>{mem_used_percent:.2f}%</span>"
}

ethernet _first_ {
        format_up = "E: %ip (%speed)"
        format_down = ""
}
